### ISSUE TITLE
No loadout button when selecting survivor

### ISSUE THREAD

**Issue by xavieraiden** [prodzpod/RadiantMalignance#1]
Title pretty much says it all. My friend is having an issue where when selecting survivor there is no loadout button, meaning they can't change the skills/abilities for survivors. Image for reference. Log should also be attached.
The only 3 mods we have enabled that aren't part of the modpack are SareSuite, RTAutoSprintEx and EmptyChestsBegone. I have all the same mods he does and am having no issues whatsoever.

![image](https://user-images.githubusercontent.com/45552520/215703114-d122f1cb-3182-4f6e-843b-be80186e13fd.png)
[LogOutput.log](https://github.com/prodzpod/RadiantMalignance/files/10544190/LogOutput.log)

**Comment by prodzpod** [comment]
intended behaviour. Loadouts are disabled on the first run as a measure to slowly introduce mechanics. just play a single run (you can quit out immediately if you want) to unlock it.

**Comment by xavieraiden** [comment]
Good to know, thanks. Will relay this to mentioned friend
