### ISSUE TITLE
"Huntress: agility not required" special loadout unlock not firing

### ISSUE THREAD

**Issue by NoWrinklesOnBrain** [prodzpod/RadiantMalignance#5]
Achievement requires to complete the first stage (which i understand as finishing the teleporter and getting off the first stage) without sprinting, however no matter what i try (no jumping and no abilities at all besides M1) it won't fire. Now i'm either stupid or the trigger is broken. On top of making sure im not using abilities or toggling sprint i've kept track of the momentum stacks to make sure i don't have any.
I'm pretty sure my install is fine since i didnt update my mods as is advised.
Now is there somewhere i can see the exact trigger for the achievement or something like that
Thanks in advance, and sorry for the text wall, its just bugging me

**Comment by prodzpod** [comment]
its probably a bug, wait for next build lol

**Comment by NoWrinklesOnBrain** [comment]
fair enough lol
